# Generated by Django 5.2 on 2025-09-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='U0sLEHu2CU2Xy3TXeUOp0lCQGT9aopkl', editable=False, max_length=32, unique=True),
        ),
    ]
