# Generated by Django 5.2 on 2025-09-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='LwjlyGWP4vIXJvXtl1g1ZbTfhAREFdyQ', editable=False, max_length=32, unique=True),
        ),
    ]
