# Generated by Django 5.2 on 2025-09-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='YVljRpcNnMpjOhKypMgK7s0QoPR0g5ne', editable=False, max_length=32, unique=True),
        ),
    ]
